backend:
  name: git-gateway
  repo: jonathanharrell/cjarellano-v2
  branch: master
local_backend: true
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: content/categories
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Action", name: "action", widget: "string", hint: "The gerund form. This will be used behind the scenes for filtering." }
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Public", name: "public", widget: "boolean", default: true, hint: "Whether or not this category should appear in sections throughout the site where project categories are listed." }
      - label: "Reels"
        name: "reels"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Video", name: "video", widget: "string", hint: "A Vimeo or YouTube URL." }
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", hint: "This will be used for SEO (it may show up as the description of this page in Google." }
      - { label: "Type", name: "type", widget: "string" }
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "categories"
        multiple: true
        search_fields: [ "action" ]
        value_field: "action"
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Video", name: "video", widget: "string", required: false, hint: "A Vimeo or YouTube URL." }
      - label: "Quotes"
        name: "quotes"
        widget: "list"
        fields:
          - { label: "Text", name: "text", widget: "string", hint: "The quote itself." }
          - { label: "Source", name: "source", widget: "string", hint: "Who said it?" }
      - label: "Awards"
        name: "awards"
        widget: "list"
        fields:
          - { label: "Source", name: "source", widget: "string", hint: "The organization awarding the committee." }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "markdown", required: false, hint: "The text of a writing sample." }
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Source", name: "source", widget: "string" }
          - label: "Social Media Posts"
            name: "posts"
            widget: "list"
            fields:
              - { label: "URL", name: "url", widget: "string", hint: "A Tweet or Facebook post." }
